blank_issues_enabled: true
contact_links:
  - name: â¤ï¸ æ„Ÿè°¢ chsrc
    url: https://github.com/RubyMetric/chsrc/discussions/categories/%E6%84%9F%E8%B0%A2-chsrc
    about: chsrc æ˜¯å¦å¸®åŠ©åˆ°äº†ä½ ï¼Ÿ
  - name: ğŸš€ èµèµæ”¯æŒ chsrc
    url: https://github.com/ccmywish/support-my-oss-work
    about: é€šè¿‡ç»æµæ”¯æŒå¸®åŠ©ä½œè€…æ›´å¥½çš„å¼€å‘å’Œç»´æŠ¤ chsrc
