# ---------------------------------------------------------------
# Workflow File : build-on-Linux-riscv64.yml
# File Authors  :  Aoran Zeng <ccmywish@qq.com>
# Contributors  :   Nul None  <nul@none.org>
#               |
# Created On    : <2023-09-14>
# Last Modified : <2025-03-06>
#
# Build chsrc on Linux (riscv64) and upload it to GitHub: the 'pre' release
# ---------------------------------------------------------------

name: Build on Linux riscv64
on:
  push:
    branches: [ "gh-build" ]
  pull_request:
    branches: [ "gh-build" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu_latest

          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apt-get update -qq
            apt-get install build-essential -y -q
            apt-get install git -y -q
            pwd ; ls -al
            git clone https://github.com/RubyMetric/chsrc -b gh-build -q
            cd chsrc
            make CI CI_ARTIFACT_NAME=chsrc-riscv64-linux
            cp ./chsrc-riscv64-linux /artifacts

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: pre
          files: |
            ./artifacts/chsrc-riscv64-linux
          token: ${{ secrets.UPLOAD_TO_GITHUB }}
