# ---------------------------------------------------------------
# Workflow File : build-on-macOS.yml
# File Authors  :  Aoran Zeng <ccmywish@qq.com>
# Contributors  :   Nul None  <nul@none.org>
#               |
# Created On    : <2023-09-15>
# Last Modified : <2025-07-22>
#
# Build chsrc on macOS and upload it to GitHub: the 'pre' release
# ---------------------------------------------------------------

name: 构建于 macOS
on:
  push:
    branches: [ "gh-build" ]

jobs:
  on-arm64:
    runs-on: macos-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检查 Clang 版本
      run: |
        clang --version

    - name: 检查 GCC 版本
      run: |
        gcc --version

    - name: 为 arm64 (AArch64) 构建
      run: |
        make build-in-ci-release-mode
        mv chsrc-ci-release chsrc-aarch64-macos

    - name: List files
      run: ls *-macos

    - name: 上传至 'pre' release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-aarch64-macos
        token: ${{ secrets.UPLOAD_TO_GITHUB }}


  on-x64:
    runs-on: macos-13 # macos-14 is AArch64(ARMv8-A)

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 检查 Clang 版本
      run: |
        clang --version

    - name: 检查 GCC 版本
      run: |
        gcc --version

    - name: 为 x64 构建
      run: |
        make build-in-ci-release-mode
        mv chsrc-ci-release chsrc-x64-macos

    - name: List files
      run: ls *-macos

    - name: 上传至 'pre' release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-x64-macos
        token: ${{ secrets.UPLOAD_TO_GITHUB }}
