# ---------------------------------------------------------------
# Workflow File : build-on-Linux-x64.yml
# File Authors  :  Aoran Zeng <ccmywish@qq.com>
# Contributors  :   Nul None  <nul@none.org>
#               |
# Created On    : <2023-09-14>
# Last Modified : <2025-06-16>
#
# Build chsrc on Linux (x64) and upload it to GitHub: the 'pre' release
# ---------------------------------------------------------------

name: 构建于 Linux x64
on:
  push:
    branches: [ "gh-build" ]
  pull_request:
    branches: [ "gh-build" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 构建
      run: |
        make CI CI_ARTIFACT_NAME=chsrc-x64-linux

    - name: List files
      run: ls *-linux

    - name: 上传至 'pre' release
      uses: softprops/action-gh-release@v2
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: pre
        files: |
          chsrc-x64-linux
        token: ${{ secrets.UPLOAD_TO_GITHUB }}
