# ---------------------------------------------------------------
# Workflow File : build-on-Linux-AArch64.yml
# File Authors  : 曾奥然 <ccmywish@qq.com>
# Contributors  : Nul None <nul@none.org>
#               |
# Created On    : <2023-09-14>
# Last Modified : <2025-09-12>
#
# Build chsrc on Linux (AArch64) and upload it to GitHub: the 'pre' release
# ---------------------------------------------------------------

name: 构建于 Linux AArch64
on:
  push:
    branches: [ "gh-build" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: 构建
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: aarch64
          distro: ubuntu_latest

          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          run: |
            apt-get update -qq
            apt-get install build-essential -y -q
            apt-get install git -y -q
            pwd ; ls -al
            git clone https://github.com/RubyMetric/chsrc -b gh-build -q
            cd chsrc

            make build-in-ci-release-mode
            mv chsrc-ci-release chsrc-aarch64-linux

            cp ./chsrc-aarch64-linux /artifacts

      - name: 上传至 'pre' release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre
          files: |
            ./artifacts/chsrc-aarch64-linux
          token: ${{ secrets.UPLOAD_TO_GITHUB }}
